import './scss/style.scss'
import './js/video'
// import './js/test'
import './js/welcome-slider'
import './js/explore-slider'
import './js/gallery'
import './js/popup'
import './js/styling'
import './js/header'